# https://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_spring_cloud_gateway

server.port: 38080

rest.api.names: school,student 

spring: 
  cloud: 
    gateway: 
      routes:
      # =====================================
      - id: service_to_school
        uri: http://localhost:18080
        order: 1000
        predicates:
        - Path=/school/**
        filters:
        - PrefixPath=/api
      # =====================================
      - id: service_to_student
        uri: http://localhost:28080
        order: 1000
        predicates:
        - Path=/student/**
        filters:
        - PrefixPath=/api
      # =====================================
      - id: service_to_school_openapi
        uri: http://localhost:18080
        order: 1000
        predicates:
        - Path=/openapi/school/**
        filters:
        - StripPrefix=2
      # =====================================
      - id: service_to_student_openapi
        uri: http://localhost:28080
        order: 1000
        predicates:
        - Path=/openapi/student/**
        filters:
        - StripPrefix=2
      